package api

import (
	"fmt"
	"os"
	"reflect"
	"strings"
)

// GenerateTS automatically generates a TypeScript API client and type interfaces
// for all registered services, ensuring end-to-end type safety between Go and JS.
func (r *Registry) GenerateTS(outputPath string) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by Glyra API Bridge. DO NOT EDIT.\n\n")

	typeReg := &typeRegistry{
		structs: make(map[string]reflect.Type),
	}

	// 1. Collect all types
	for _, service := range r.services {
		typ := reflect.TypeOf(service)
		for i := 0; i < typ.NumMethod(); i++ {
			method := typ.Method(i)
			for j := 1; j < method.Type.NumIn(); j++ {
				typeReg.register(method.Type.In(j))
			}
			for j := 0; j < method.Type.NumOut(); j++ {
				typeReg.register(method.Type.Out(j))
			}
		}
	}

	// 2. Generate Struct Interfaces
	for name, t := range typeReg.structs {
		sb.WriteString(fmt.Sprintf("export interface %s {\n", name))
		for i := 0; i < t.NumField(); i++ {
			field := t.Field(i)
			// Handle json tags if present
			jsonTag := field.Tag.Get("json")
			fieldName := field.Name
			if jsonTag != "" && jsonTag != "-" {
				fieldName = strings.Split(jsonTag, ",")[0]
			}
			if jsonTag != "-" {
				sb.WriteString(fmt.Sprintf("  %s: %s;\n", fieldName, goTypeToTS(field.Type)))
			}
		}
		sb.WriteString("}\n\n")
	}

	// 3. Global window declarations
	sb.WriteString("declare global {\n")
	sb.WriteString("  interface Window {\n")
	for name, service := range r.services {
		typ := reflect.TypeOf(service)
		for i := 0; i < typ.NumMethod(); i++ {
			method := typ.Method(i)
			bindName := fmt.Sprintf("%s_%s", name, method.Name)
			args, ret := getTSSignature(method.Type)
			sb.WriteString(fmt.Sprintf("    %s: (%s) => Promise<%s>;\n", bindName, args, ret))
		}
	}
	sb.WriteString("  }\n")
	sb.WriteString("}\n\n")

	// 4. Generate clean Client objects
	for name, service := range r.services {
		sb.WriteString(fmt.Sprintf("export const %s = {\n", name))
		typ := reflect.TypeOf(service)
		for i := 0; i < typ.NumMethod(); i++ {
			method := typ.Method(i)
			bindName := fmt.Sprintf("%s_%s", name, method.Name)
			args, _ := getTSSignature(method.Type)
			
			var argNames []string
			for j := 1; j < method.Type.NumIn(); j++ {
				argNames = append(argNames, fmt.Sprintf("arg%d", j))
			}
			argsList := strings.Join(argNames, ", ")

			sb.WriteString(fmt.Sprintf("  %s: (%s) => window.%s(%s),\n", method.Name, args, bindName, argsList))
		}
		sb.WriteString("};\n\n")
	}

	return os.WriteFile(outputPath, []byte(sb.String()), 0644)
}

type typeRegistry struct {
	structs map[string]reflect.Type
}

func (tr *typeRegistry) register(t reflect.Type) {
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	if t.Kind() == reflect.Struct && t.Name() != "" && t.Name() != "error" {
		if _, ok := tr.structs[t.Name()]; !ok {
			tr.structs[t.Name()] = t
			for i := 0; i < t.NumField(); i++ {
				tr.register(t.Field(i).Type)
			}
		}
	} else if t.Kind() == reflect.Slice || t.Kind() == reflect.Array {
		tr.register(t.Elem())
	} else if t.Kind() == reflect.Map {
		tr.register(t.Key())
		tr.register(t.Elem())
	}
}

func getTSSignature(m reflect.Type) (string, string) {
	var args []string
	for i := 1; i < m.NumIn(); i++ {
		args = append(args, fmt.Sprintf("arg%d: %s", i, goTypeToTS(m.In(i))))
	}
	
	retType := "void"
	if m.NumOut() > 0 {
		firstOut := m.Out(0)
		if firstOut.Name() == "error" {
			retType = "void"
		} else {
			retType = goTypeToTS(firstOut)
		}
	}

	return strings.Join(args, ", "), retType
}

func goTypeToTS(t reflect.Type) string {
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	if t.Name() == "error" {
		return "string"
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Bool:
		return "boolean"
	case reflect.Slice, reflect.Array:
		return goTypeToTS(t.Elem()) + "[]"
	case reflect.Map:
		return fmt.Sprintf("Record<%s, %s>", goTypeToTS(t.Key()), goTypeToTS(t.Elem()))
	case reflect.Struct:
		if t.Name() == "" {
			return "any"
		}
		return t.Name()
	case reflect.Interface:
		return "any"
	default:
		return "any"
	}
}
